#pragma kernel Physics

struct Main_Buffer
{
    float4 id;
    float4 position;
    float4 velocity;
    float4 rotation;
    float4 angularVelocity;
    float4 mass_drag_additionalIndex_updateMask;
};
struct Additional_Buffer
{
    float4 data0;
    float4 data1;
    float4 data2;
    float4 data3;
};

RWStructuredBuffer<Main_Buffer> MainBuffer;
RWStructuredBuffer<Additional_Buffer> AdditionalBuffer;

RWStructuredBuffer<int> ActiveIndices;
RWStructuredBuffer<uint> TaskCounter;
RWStructuredBuffer<uint> ActiveCount;

float _DeltaTime;
float3 _Gravity;
float3 _MouseDelta;

void Gravity(inout Main_Buffer _bufferSegment)
{
    Main_Buffer b = _bufferSegment;
    b.velocity.y += _Gravity.y * _DeltaTime;
    b.position.y += b.velocity.y * _DeltaTime;
    b.position.w = 1;
    b.velocity.w = 1;
    _bufferSegment = b;
}

void Default(inout Main_Buffer _bufferSegment)
{
    _bufferSegment.mass_drag_additionalIndex_updateMask.w = 0;
}

void OrbitCS(inout Main_Buffer _bufferSegment)
{
    if (_MouseDelta.z)
    {
        _MouseDelta.z = 0;

        Main_Buffer main = _bufferSegment;

        int addIdx = (int) main.mass_drag_additionalIndex_updateMask.z;
        Additional_Buffer add = AdditionalBuffer[addIdx];

        float flag = add.data2.w;
        if (!flag) return;

        float2 angle = add.data0.zw;
        float torque = add.data1.x;
        float radius = add.data1.y;
        float3 center = add.data2.xyz;

        float newAngleX = angle.x + _MouseDelta.x * torque;
        float newAngleY = angle.y + _MouseDelta.y * torque;
        newAngleY = clamp(newAngleY, -80.0, 80.0);

        float angleXRad = radians(newAngleX);
        float angleYRad = radians(newAngleY);

        float cosX, sinX, cosY, sinY;
        sincos(angleXRad, sinX, cosX);
        sincos(angleYRad, sinY, cosY);

        float rCosY = radius * cosY;
        float3 offset;
        offset.x = rCosY * sinX; 
        offset.y = -radius * sinY;
        offset.z = -rCosY * cosX;

        main.position.xyz = center + offset;
        main.position.w = 1;

        main.rotation.x = newAngleX;
        main.rotation.y = newAngleY;
        main.rotation.z = 0;
        main.rotation.w = 1;

        add.data0.zw = float2(newAngleX, newAngleY);
        
        main.mass_drag_additionalIndex_updateMask.w = 12;
        
        _bufferSegment = main;
        AdditionalBuffer[addIdx] = add;
    }
    else _bufferSegment.mass_drag_additionalIndex_updateMask.w = 0;
}

[numthreads(64, 1, 1)]
void Physics(uint3 id : SV_DispatchThreadID)
{
    while (true)
    {
        uint mySlot;
        InterlockedAdd(TaskCounter[0], 1, mySlot);

        if (mySlot >= ActiveCount[0]) break;

        int objIdx = ActiveIndices[mySlot];

        if (objIdx < 0) continue;

        Main_Buffer seg = MainBuffer[objIdx];

        for (int i = 0; i < 4; i++)
        {
            switch (seg.id[i])
            {
                case 0: break;
                case 1: OrbitCS(seg); break;
                case 3: Gravity(seg); break;
                default: Default(seg); break;
            }
        }
        MainBuffer[objIdx] = seg;
    }
}