#pragma kernel Main0
#pragma kernel Main1

#include "Assets/Infrastructure/Phisics/HLSL_Logic/IncludesTree.hlsl"

[numthreads(64, 1, 1)]
void Main0(uint3 id : SV_DispatchThreadID)
{
    while (true)
    {
        uint index;
        InterlockedAdd(threadsCounter0Buffer[0], 1, index);
        
        if (index >= orchestrator_buffer_size) break;
        
        uint indexInBuffer = index / 4;
        int slotIndex = index % 4;
        uint4 element = indexAdditionalDataBuffer[indexInBuffer];
        
        uint packedValue;
        
        switch (slotIndex)
        {
            case 0: packedValue = element.index0; break;
            case 1: packedValue = element.index1; break;
            case 2: packedValue = element.index2; break;
            case 3: packedValue = element.index3; break;
        }
        uint4 ele
        ReadOperation(packedValue);
    }
}
[numthreads(64, 1, 1)]
void Main1(uint3 id : SV_DispatchThreadID)
{
    while (true)
    {
        uint index;
        InterlockedAdd(threadsCounter1Buffer[0], 1, index);
        
        if (index >= orchestrator_buffer_size) break;
        
        uint indexInBuffer = index / 4;
        int slotIndex = index % 4;
        uint4 element = indexAdditionalDataBuffer[indexInBuffer];
        
        uint packedValue;
        
        switch (slotIndex)
        {
        case 0: packedValue = element.index0; break;
        case 1: packedValue = element.index1; break;
        case 2: packedValue = element.index2; break;
        case 3: packedValue = element.index3; break;
        }
        ReadOperation(packedValue);
    }
}